const adventuresData = {
  woodlands: {
    storyTitle: "woodlands",
    storyName: "woodlands",
    storyId: "w",
    storyIdLong: "o0001",
    author: "youngladino",
    coverimgPortrait: "./public/images/portrait/w001p.png",
    coverimgLandscape: "./public/images/landscape/w001l.png",
    storyText:
      "you start your journey on a peaceful and open path through a cold forest. The sky is blue, the air is crispy. In front of you a massive mountain range emerges from the depths of a turquoise glacier lake. Serenity is only interrupted by the sound of nails being hammered in the old planks on an ominous cabin not so distant in the woods. As you shiver, you are being watched from high up.",
    storyDescription: "",
    author: "youngladino",
    dateAdded: "2024-01-18",
    adventuresInside: {
      w001: {
        adventureName: "a nice day",
        adventureId: "w001",
        adventureStoryId: "w",
        adventureLevel: 0,
        adventureBranch: 0,
        adventureNumber: 1,
        adventureimgPortrait: "./public/images/portrait/w001p.png",
        adventureimgLandscape: "",
        adventureText: "lorem",
        adventureDescription: "loremlong",
        adventurePrior: "",
        adventureAfter: ["w101"],
        creepy: false,
        author: "youngladino",
        dateAdded: "2024-01-17",
      },
      w101: {
        adventureName: "something looks off",
        adventureId: "w101",
        adventureStoryId: "w",
        adventureLevel: 1,
        adventureBranch: 0,
        adventureNumber: 1,
        adventureimgPortrait: "./public/images/portrait/w101p.png",
        adventureimgLandscape: "",
        adventureText: "lorem",
        adventureDescription: "loremlong",
        adventurePrior: "w001",
        adventureAfter: ["w201"],
        creepy: false,
        author: "youngladino",
        dateAdded: "2024-01-16",
      },

      w201: {
        adventureName: "hospitality or not",
        adventureId: "w201",
        adventureStoryId: "w",
        adventureLevel: 2,
        adventureBranch: 0,
        adventureNumber: 1,
        adventureimgPortrait: "./public/images/portrait/w201p.png",
        adventureimgLandscape: "./public/images/landscape/w201l.png",
        adventureText: "lorem",
        adventureDescription: "loremlong",
        adventurePrior: "w101",
        adventureAfter: ["w301"],
        creepy: false,
        author: "youngladino",
        dateAdded: "2024-01-16",
      },
      w301: {
        adventureName: "a bad dream, a worse awakening",
        adventureId: "w301",
        adventureStoryId: "w",
        adventureLevel: 3,
        adventureBranch: 0,
        adventureNumber: 1,
        adventureimgPortrait: "./public/images/portrait/w301p.png",
        adventureimgLandscape: "",
        adventureText: "lorem",
        adventureDescription: "loremlong",
        adventurePrior: "w201",
        adventureAfter: [],
        creepy: true,
        author: "youngladino",
        dateAdded: "2024-01-18",
      },
    },
  },
  futuristicCity: {
    storyTitle: "futuristicCity",
    storyName: "A day in the city of the future",
    storyId: "fc",
    storyIdLong: "o0002",
    author: "youngladino",
    coverimgPortrait: "./public/images/portrait/fc001p.png",
    coverimgLandscape: "./public/images/landscape/fc001l.png",
    storyText:
      "As dawn breaks over the futuristic city, you awaken in a high-tech bedroom atop a towering skyscraper. Outside, flying cars glide through the morning sky, signaling an adventure-filled day ahead. A mysterious holographic message flickers into view, hinting at secrets deep within the city. Unbeknownst to you, this day will embark you on an extraordinary journey, threading through wonders and dangers, reshaping your destiny.",
    storyDescription: "",
    author: "youngladino",
    dateAdded: "2024-01-18",
    adventuresInside: {
      fc001: {
        adventureName: "good future morning",
        adventureId: "fc001",
        adventureStoryId: "fc",
        adventureLevel: 0,
        adventureBranch: 0,
        adventureNumber: 1,
        adventureimgPortrait: "./public/images/portrait/fc001p.png",
        adventureimgLandscape: "./public/images/landscape/fc001l.png",
        adventureText: "lorem",
        adventureDescription: "loremlong",
        adventurePrior: "",
        adventureAfter: ["fc101"],
        creepy: false,
        author: "youngladino",
        dateAdded: "2024-01-18",
      },
      fc101: {
        adventureName: "eggs and servers",
        adventureId: "fc101",
        adventureStoryId: "fc",
        adventureLevel: 1,
        adventureBranch: 0,
        adventureNumber: 1,
        adventureimgPortrait: "./public/images/portrait/fc101p.png",
        adventureimgLandscape: "./public/images/landscape/fc101l.png",
        adventureText: "lorem",
        adventureDescription: "loremlong",
        adventurePrior: ["fc001"],
        adventureAfter: ["fc201"],
        creepy: false,
        author: "youngladino",
        dateAdded: "2024-01-18",
      },
      fc201: {
        adventureName: "out and about",
        adventureId: "fc201",
        adventureStoryId: "fc",
        adventureLevel: 2,
        adventureBranch: 0,
        adventureNumber: 1,
        adventureimgPortrait: "./public/images/portrait/fc201p.png",
        adventureimgLandscape: "./public/images/landscape/fc201l.png",
        adventureText: "lorem",
        adventureDescription: "loremlong",
        adventurePrior: ["fc101"],
        adventureAfter: ["fc301"],
        creepy: false,
        author: "youngladino",
        dateAdded: "2024-01-18",
      },
    },
  },
};
export default adventuresData;
