const adventuresData = {
  woodlands: {
    storyName: "woodlands",
    storyId: "w",
    author: "youngladino",
    coverimgPortrait: "./public/images/portrait/w001p.png",
    coverimgLandscape: "./public/images/landscape/w001l.png",
    storyText:
      "you start your journey on a peaceful and open path through a cold forest. The sky is blue, the air is crispy. In front of you a massive mountain range emerges from the depths of a turquoise glacier lake. Serenity is only interrupted by the sound of nails being hammered in the old planks on an ominous cabin not so distant in the woods. As you shiver, you are being watched from high up.",
    storyDescription: "",
    adventuresInside: {
      w001: {
        adventureName: "a nice day",
        adventureId: "w001",
        adventureStoryId: "w",
        adventureLevel: 0,
        adventureBranch: 0,
        adventureNumber: 1,
        adventureimgPortrait: "./public/images/portrait/w001p.png",
        adventureimgLandscape: "",
        adventureText: "lorem",
        adventureDescription: "loremlong",
        adventurePrior: "",
        adventureAfter: ["w101"],
        author: "youngladino",
        dateAdded: "2024-01-17",
      },
      w101: {
        adventureName: "something looks off",
        adventureId: "w101",
        adventureStoryId: "w",
        adventureLevel: 1,
        adventureBranch: 0,
        adventureNumber: 1,
        adventureimgPortrait: "./public/images/portrait/w101p.png",
        adventureimgLandscape: "",
        adventureText: "lorem",
        adventureDescription: "loremlong",
        adventurePrior: "w001",
        adventureAfter: ["w201"],
        author: "youngladino",
        dateAdded: "2024-01-16",
      },

      w201: {
        adventureName: "hospitality or not",
        adventureId: "w201",
        adventureStoryId: "w",
        adventureLevel: 2,
        adventureBranch: 0,
        adventureNumber: 1,
        adventureimgPortrait: "./public/images/portrait/w201p.png",
        adventureimgLandscape: "./public/images/landscape/w201l.png",
        adventureText: "lorem",
        adventureDescription: "loremlong",
        adventurePrior: "w101",
        adventureAfter: [],
        author: "youngladino",
        dateAdded: "2024-01-16",
      },
    },
  },
};
export default adventuresData;
